[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/matches"
  to = "/.netlify/functions/matches"
  status = 200

[[redirects]]
  from = "/api/pronostic"
  to = "/.netlify/functions/pronostic"
  status = 200
